### ISSUE TITLE
Using sso tickets with v14.

### ISSUE THREAD

**Issue by Alex-Habbz** [Quackster/Kepler#45]

**Comment by Alex-Habbz** [comment]
So I decided to try out 1.4 and everything works fine but when logged in using sso ticket you cant update your looks/figure, not sure if this is intended or a bug.

**Comment by Quackster** [comment]
It's not a bug with Kepler, it's the way the client behaves, because if you're using an SSO ticket then the client assumes you're using a website - where it has the features to change the clothes on the site itself instead of inside the client.

**Comment by Quackster** [comment]
It seems the client doesn't send back an update packet once OK is pressed. I'll look into it.

I will say, it doesn't at first seem like a bug with Kepler, but rather a bug with the client itself.

**Comment by Quackster** [comment]
So if you're using SSO tickets, you are using a CMS, so you should open the settings table and set

"profile.editing" => false

And then when people click edit looks, it will open a web page to where they should edit their clothes instead, not from within the client.

The reason why you can't change looks from inside the client when using SSO tickets, is because the client uses the password you entered in (the old fashioned login way) to verify it's actually you when changing email/password - and since you're logging in via SSO this information isn't available. I can verify this myself when looking at the decompiled source code of the v14 client.
