### ISSUE TITLE
Bugs/issues I've found.

### ISSUE THREAD

**Issue by Habbz1** [Quackster/Kepler#5]
**1.** I've noticed that club gifts have stopped working on latest release and now when you accept a gift the emulator just throws a null pointer exception.
**2.** Battleships and poker DC you, I understand that you probably haven't got around to adding the packets for them yet but if you did that would be amazing.
**3.** When entering the lido pool and crossing pass the diving line and then exiting the pool your still be swimming.
**4.** Camera isn't taking a photo and just forever says saving photo.

**5. My biggest issue:** I purchased two TCP proxys to use with the server, one for the game server and the other for MUS, every now and again my users just DC randomly for no reason, I assume this is because of the proxys but I cant imagine not using them on a public server as I like to have the most amount of security possible. Are you going to be implementing them properly like Arcturus for example? So that the emulator gets given the users real IP address. **(This happens quite frequently and is very annoying!)**

**Comment by emansom** [comment]
Could you eleborate on how Arcturus properly handles TCP proxies? Does it support HAProxy's PROXYv2 protocol?

**Comment by Habbz1** [comment]
I believe so yeh, on Arcturus database in the settings they have a row
called tcp proxy which I set to 1 to enable so every time a user enters the
hotel on Arcturus, their real IP is logged and not the TCP proxy IP, at the
moment on Kepler I have the connection per IP set to like 99999 because
Kepler recieves the proxy IP and treats it all like one connection which is
why I think im having issues with users DC all the time.

**Comment by Alex-Habbz** [comment]
I've fixed the DC issue for the moment by using Radmin VPN so everyone connects through that VPN but will be cool if you can implement TCP proxys as then I wont need to use extra software.

**Comment by Quackster** [comment]
**_I've noticed that club gifts have stopped working on latest release and now when you accept a gift the emulator just throws a null pointer exception._**

Gift clubs and camera photos have been fixed, run this SQL I've attached.

[missing_item_definitions.txt](https://github.com/Quackster/Kepler/files/2779034/missing_item_definitions.txt)

**_Battleships and poker DC you, I understand that you probably haven't got around to adding the packets for them yet but if you did that would be amazing._**

Neither cause disconnections here, and neither are coded. Your proxy is probably causing it.

**_When entering the lido pool and crossing pass the diving line and then exiting the pool your still be swimming_**

Yes I'm aware of it.

_**Camera isn't taking a photo and just forever says saving photo.**_

See first response.

_**Are you going to be implementing them properly like Arcturus for example? So that the emulator gets given the users real IP address.**_

The random disconnects are nothing to do my server, only your proxy, and my server cannot know the origin IP address that's being passed from the proxy, it's not impossible. In the case of Arcturus, the IP is probably logged the IP from the website/CMS instead of the server itself

**Comment by Quackster** [comment]
Run this to fix the colours for the gifts as well.

[present_definition_fix.txt](https://github.com/Quackster/Kepler/files/2779920/present_definition_fix.txt)

**Comment by Habbz1** [comment]
Awesome thank you for the explanations, amazing server, love it. Keep up the good work!

**Comment by Habbz1** [comment]
Room votes is also displaying a null pointer exception.

Also is there a way to grab the users online from database?

**Comment by gazsux** [comment]
@Habbz1 
Just add all the values in the `visitors_now` column of the `rooms` table in the database and echo them with a PHP script and SQL query. I also added a `setInterval` function with jquery and refreshed the call to the PHP script every few seconds so it updates in real-time.
