### ISSUE TITLE
Shockwave .exe client

### ISSUE THREAD

**Issue by FrnkRage** [Quackster/Kepler#8]
Hello,

does anyone know how I can create a .exe client that provides login at my retro made with Kepler (shockwave)?

Example classic habbo:
https://classichabbo.com/classichabbo_exe.zip

I appreciate the mac compatibility.

**Comment by Quackster** [comment]
I won't share it because it's my own work, however, what I did was essentially learnt some lingo, created my own movie in Director MX 2004 and used this Xtra (linked below) for setting the parameters to make the loader work, and also it does a HTTP request to grab an SSO ticket and apply it using "setExternalParam" with the same values like you see in your typical HTML client loader. And then published it as a projector, to make it work standalone.

https://github.com/tomysshadow/LeechProtectionRemovalHelp-Xtra

Please also have a look at: https://h4bbo.net/shockwave.html

Particularly Director MX 2004 to use this Xtra.

This isn't an issue related to Kepler so I'm going to close it.

EDIT 18/06/2024: Moved from alex-dev.org to h4bbo.net
